services:
  - type: web
    name: memoro
    runtime: node
    plan: free
    region: oregon
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: NODE_ENV=production node .next/standalone/server.js
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: NEXTAUTH_SECRET
        generateValue: true
      - key: NEXTAUTH_URL
        fromService:
          name: memoro
          type: web
          property: host
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: NODE_ENV
        value: production
